trigger:
- main

pool:
  name: 'Default'

variables:
  dockerRegistryServiceConnection: 'dockerhub-conn'
  imageRepository: 'jhostterv/app-backend'
  containerRegistry: 'docker.io'
  dockerfilePath: '$(Build.SourcesDirectory)/backend/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Quality_and_Scripts
  jobs:
  - job: ParallelMessages
    strategy:
      parallel: 10
    steps:
    - script: echo "Escribiendo desde la instancia $(System.JobPositionInPhase)"
      displayName: 'Punto A: Mensaje Paralelo'

  - job: FileCreation
    steps:
    - bash: |
        echo "Iniciando creación de archivos..."
        for i in {1..10}
        do
          FECHA=$(date +"%Y-%m-%d_%H-%M-%S")
          NOMBRE="archivo_${i}_${FECHA}.txt"
          touch $NOMBRE
          echo "Creado: $NOMBRE"
        done
        echo "Lista de archivos creados:"
        ls -ltr archivo_*.txt
      displayName: 'Punto B: Script archivos con fecha'

  - job: SonarAnalysis
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonarqube-local'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'proyecto-backend'
        cliSources: 'backend'
    - task: SonarQubeAnalyze@5
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'

- stage: Build_and_Push
  dependsOn: Quality_and_Scripts
  condition: succeeded()
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Generar y subir imagen a DockerHub'
      inputs:
        command: 'buildAndPush'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest