trigger:
- main

pool:
  name: 'Default'

variables:
  dockerRegistryServiceConnection: 'dockerhub-conn'
  imageRepository: 'jhostterv/pruebadummy'
  containerRegistry: 'docker.io'
  dockerfilePath: '$(Build.SourcesDirectory)/backend/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Quality_and_Scripts
  jobs:
  - job: ParallelMessages
    strategy:
      parallel: 10
    steps:
    - script: echo "Escribiendo desde la instancia $(System.JobPositionInPhase)"
      displayName: 'Punto A: Mensaje Paralelo'

  - job: FileCreation
    steps:
    - bash: |
        echo "Iniciando creación de archivos..."
        for i in {1..10}
        do
          FECHA=$(date +"%Y-%m-%d_%H-%M-%S")
          NOMBRE="archivo_${i}_${FECHA}.txt"
          touch $NOMBRE
          echo "Creado: $NOMBRE"
        done
        echo "Lista de archivos creados:"
        ls -ltr archivo_*.txt
      displayName: 'Punto B: Script archivos con fecha'

  - job: SonarAnalysis
    steps:
    - bash: |
        echo "Ejecutando escáner manual para evitar error de ramas en v8..."
        # Usamos el ejecutable que la tarea Prepare ya dejó listo
        $(SonarQubePrepare.sonarScannerPath) \
          -Dsonar.projectKey=dummy_devops \
          -Dsonar.sources=backend \
          -Dsonar.host.url=http://192.168.107.20:9000 \
          -Dsonar.login=$TOKEN_DE_SONAR \
          -Dsonar.scm.provider=none
      displayName: 'Bypass de Análisis SonarQube'
      env:
        TOKEN_DE_SONAR: $(SONAR_TOKEN) 
    - task: SonarQubePublish@8
      inputs:
        pollingTimeoutSec: '300'
        
- stage: Build_and_Push
  dependsOn: Quality_and_Scripts
  condition: succeeded()
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Generar y subir imagen a DockerHub'
      inputs:
        command: 'buildAndPush'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest